"""
Contains match-related data and how to connect to the database and create table.
Used for retrieving and managing fantasy match information.
"""

import sqlite3
connection_object = sqlite3.connect('FantasyCricketGame.db')
cursor_object = connection_object.cursor()
cursor_object.execute('''CREATE TABLE IF NOT EXISTS Matches(Match Text(20),Players Text(1000),Points INTEGER);''')
connection_object.commit()
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match1','Kohli',52);''')
cursor_object.execute( '''INSERT INTO Matches(Match,Players,Points) VALUES('Match2','Kohli',88);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match3','Kohli',34);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match4','Kohli',76);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match5','Kohli',41);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match6','Kohli',95);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match1','Yuvraj',45);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match2','Yuvraj',60);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match3','Yuvraj',22);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match4','Yuvraj',71);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match5','Yuvraj',38);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match6','Yuvraj',54);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match1','Rahane',30);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match2','Rahane',55);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match3','Rahane',18);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match4','Rahane',62);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match5','Rahane',44);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match6','Rahane',40);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match1','Dhawan',66);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match2','Dhawan',49);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match3','Dhawan',77);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match4','Dhawan',28);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match5','Dhawan',58);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match6','Dhawan',63);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match1','Dhoni',40);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match2','Dhoni',35);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match3','Dhoni',55);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match4','Dhoni',48);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match5','Dhoni',60);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match6','Dhoni',72);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match1','Axar',28);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match2','Axar',42);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match3','Axar',39);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match4','Axar',51);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match5','Axar',44);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match6','Axar',46);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match1','Pandya',72);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match2','Pandya',64);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match3','Pandya',81);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match4','Pandya',33);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match5','Pandya',90);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match6','Pandya',58);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match1','Jadeja',55);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match2','Jadeja',47);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match3','Jadeja',60);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match4','Jadeja',70);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match5','Jadeja',66);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match6','Jadeja',59);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match1','Kedar',25);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match2','Kedar',30);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match3','Kedar',18);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match4','Kedar',40);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match5','Kedar',22);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match6','Kedar',35);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match1','Ashwin',48);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match2','Ashwin',52);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match3','Ashwin',44);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match4','Ashwin',60);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match5','Ashwin',58);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match6','Ashwin',50);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match1','Umesh',35);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match2','Umesh',28);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match3','Umesh',40);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match4','Umesh',45);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match5','Umesh',30);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match6','Umesh',38);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match1','Bumrah',65);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match2','Bumrah',70);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match3','Bumrah',55);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match4','Bumrah',80);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match5','Bumrah',75);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match6','Bumrah',68);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match1','Bhuwaneshwar',58);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match2','Bhuwaneshwar',62);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match3','Bhuwaneshwar',50);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match4','Bhuwaneshwar',66);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match5','Bhuwaneshwar',61);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match6','Bhuwaneshwar',57);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match1','Rohit',80);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match2','Rohit',90);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match3','Rohit',65);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match4','Rohit',88);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match5','Rohit',72);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match6','Rohit',95);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match1','Kartick',44);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match2','Kartick',38);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match3','Kartick',52);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match4','Kartick',47);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match5','Kartick',60);''')
cursor_object.execute('''INSERT INTO Matches(Match,Players,Points) VALUES('Match6','Kartick',55);''')
connection_object.commit()
connection_object.close()
