# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EvaluateTeam.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

"""
Handles fantasy team evaluation logic and score calculation.
Provides the main user interface for selecting players and viewing points.
"""
from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setMinimumSize(QtCore.QSize(130, 0))
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(160, 110, 121, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(Dialog)
        self.comboBox_2.setGeometry(QtCore.QRect(470, 110, 131, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(160, 240, 141, 171))
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(Dialog)
        self.listWidget_2.setGeometry(QtCore.QRect(470, 240, 151, 171))
        self.listWidget_2.setObjectName("listWidget_2")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(130, 160, 521, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(170, 200, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(490, 200, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(560, 200, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(23, 224, 255);")
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(310, 470, 150, 50))
        self.pushButton.setMinimumSize(QtCore.QSize(130, 30))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(150, 60, 451, 30))
        self.label.setMinimumSize(QtCore.QSize(300, 30))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.load_teams()
        self.comboBox.currentTextChanged.connect(self.select_team)
        self.comboBox_2.currentTextChanged.connect(self.select_match) 
        self.pushButton.clicked.connect(self.load_data)
        self.selected_team = "Select Team"
        self.selected_match = "Select Match"
        
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "EvaluateTeam"))
        self.comboBox.setItemText(0, _translate("Dialog", "Select Team"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Select Match"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Match1"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "Match2"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "Match3"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "Match4"))
        self.comboBox_2.setItemText(5, _translate("Dialog", "Match5"))
        self.comboBox_2.setItemText(6, _translate("Dialog", "Match6"))
        self.label_2.setText(_translate("Dialog", "Players"))
        self.label_3.setText(_translate("Dialog", "Points"))
        self.label_4.setText(_translate("Dialog", "0"))
        self.pushButton.setText(_translate("Dialog", "Caluclate Score"))
        self.label.setText(_translate("Dialog", "     Evaluate the Performance of your Fantasy Team"))
        
    def load_data(self):
        if self.selected_team == "Select Team" or self.selected_match == "Select Match":
             return
        self.listWidget.clear()
        self.listWidget_2.clear()
        total_points = 0
        connection_object = sqlite3.connect('FantasyCricketGame.db')
        cursor_object = connection_object.cursor()
        query = '''SELECT Players FROM Teams WHERE Name = ?'''
        cursor_object.execute(query, (self.selected_team,))
        record = cursor_object.fetchone()
        if record:
            players = record[0].split(",")
            for player in players:
                self.listWidget.addItem(player)
                query2 = '''
                SELECT Points FROM Matches
                WHERE Players = ? AND Match = ?
                '''
                cursor_object.execute(query2, (player, self.selected_match))
                point_record = cursor_object.fetchone()
                if point_record:
                    points = point_record[0]
                else:
                    points = 0
                self.listWidget_2.addItem(str(points))
                total_points += points
            connection_object.close()
        self.label_4.setText(str(total_points))
        connection_object.close()
        
    def load_teams(self):
        connection_object = sqlite3.connect('FantasyCricketGame.db')
        cursor_object = connection_object.cursor()
        query='''SELECT Name FROM Teams'''
        cursor_object.execute(query)
        record=cursor_object.fetchall()
        for i in record:
            self.comboBox.addItem(i[0])
        connection_object.commit()
        connection_object.close()
            
    def select_team(self, item):
        self.selected_team = item

    def select_match(self, item):
        self.selected_match = item

        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
