"""
Main application entry point for the Fantasy Cricket Game.
Initializes the PyQt5 GUI and launches the application window.
"""


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from EvaluateTeam import Ui_Dialog
import sqlite3

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 80))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 170, 127);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 170, 127);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 170, 127);")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(0, 170, 127);")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(0, 170, 127);")
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_2.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_2.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(0, 170, 127);")
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_2.addWidget(self.label_12)
        self.verticalLayout_3.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.widget_3.setMaximumSize(QtCore.QSize(16777215, 50))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_4.addWidget(self.radioButton)
        self.radioButton_4 = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_4.addWidget(self.radioButton_4)
        self.radioButton_2 = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_4.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.widget_3)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_4.addWidget(self.radioButton_3)
        self.verticalLayout.addWidget(self.widget_3)
        self.listWidget = QtWidgets.QListWidget(self.groupBox_3)
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 400))
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.groupBox_2 = QtWidgets.QGroupBox(self.widget_2)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_4 = QtWidgets.QWidget(self.groupBox_2)
        self.widget_4.setMaximumSize(QtCore.QSize(300, 100))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.widget_4.setFont(font)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_13 = QtWidgets.QLabel(self.widget_4)
        self.label_13.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_5.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.widget_4)
        self.label_14.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(0, 170, 127);")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_5.addWidget(self.label_14)
        self.verticalLayout_2.addWidget(self.widget_4)
        self.listWidget_2 = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget_2.setObjectName("listWidget_2")
        self.verticalLayout_2.addWidget(self.listWidget_2)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_3.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuManage_Teams = QtWidgets.QMenu(self.menubar)
        self.menuManage_Teams.setObjectName("menuManage_Teams")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNEW_Team = QtWidgets.QAction(MainWindow)
        self.actionNEW_Team.setObjectName("actionNEW_Team")
        self.actionOPEN_Team = QtWidgets.QAction(MainWindow)
        self.actionOPEN_Team.setObjectName("actionOPEN_Team")
        self.actionSAVE_Team = QtWidgets.QAction(MainWindow)
        self.actionSAVE_Team.setObjectName("actionSAVE_Team")
        self.actionEVALUATE_Team = QtWidgets.QAction(MainWindow)
        self.actionEVALUATE_Team.setObjectName("actionEVALUATE_Team")
        self.menuManage_Teams.addAction(self.actionNEW_Team)
        self.menuManage_Teams.addAction(self.actionOPEN_Team)
        self.menuManage_Teams.addAction(self.actionSAVE_Team)
        self.menuManage_Teams.addAction(self.actionEVALUATE_Team)
        self.menubar.addAction(self.menuManage_Teams.menuAction())
        self.MainWindow = MainWindow

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.groupBox_3.setEnabled(False)  #Disables All Buttons intially
        self.groupBox_2.setEnabled(False)
        self.pushButton.setEnabled(False)
        
        self.actionNEW_Team.triggered.connect(self.new_team) #When the NEW Team is clicked enable_team is triggred and get_team_name
        self.actionSAVE_Team.triggered.connect(self.save_team)
        self.actionOPEN_Team.triggered.connect(self.open_team)
        self.actionEVALUATE_Team.triggered.connect(self.evaluate_team)
        
        self.radioButton.clicked.connect(self.Players_BAT)  # When radioButtons are clicked any one of them will be executed
        self.radioButton_4.clicked.connect(self.Players_BOW)
        self.radioButton_2.clicked.connect(self.Players_AR)
        self.radioButton_3.clicked.connect(self.Players_WK)
        self.listWidget.itemClicked.connect(self.select_player) 
        self.pushButton.clicked.connect(self.move_player)
        self.listWidget_2.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.listWidget_2.customContextMenuRequested.connect(self.show_menu)
        
    def evaluate_team(self):

        self.dialog = QtWidgets.QDialog()

        self.ui = Ui_Dialog()
        self.ui.setupUi(self.dialog)

        main_width = self.MainWindow.width()
        main_height = self.MainWindow.height()

        self.dialog.resize(
            int(main_width * 0.9),
            int(main_height * 0.9)
        )

        self.dialog.exec_()
        
       
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Your Selections"))
        self.label.setText(_translate("MainWindow", "Batsmen (BAT)"))
        self.label_2.setText(_translate("MainWindow", "##"))
        self.label_3.setText(_translate("MainWindow", "Bowlers (BOW)"))
        self.label_4.setText(_translate("MainWindow", "##"))
        self.label_5.setText(_translate("MainWindow", "Allrounders (AR)"))
        self.label_6.setText(_translate("MainWindow", "##"))
        self.label_7.setText(_translate("MainWindow", "Wicket-keeper (WK)"))
        self.label_8.setText(_translate("MainWindow", "##"))
        self.label_9.setText(_translate("MainWindow", "Points Available"))
        self.label_10.setText(_translate("MainWindow", "####"))
        self.label_11.setText(_translate("MainWindow", "Points Used"))
        self.label_12.setText(_translate("MainWindow", "####"))
        self.radioButton.setText(_translate("MainWindow", "BAT"))
        self.radioButton_4.setText(_translate("MainWindow", "BOW"))
        self.radioButton_2.setText(_translate("MainWindow", "AR"))
        self.radioButton_3.setText(_translate("MainWindow", "WK"))
        self.pushButton.setText(_translate("MainWindow", ">"))
        self.label_13.setText(_translate("MainWindow", "Team Name"))
        self.label_14.setText(_translate("MainWindow", "Displayed Here"))
        self.menuManage_Teams.setTitle(_translate("MainWindow", "Manage Teams"))
        self.actionNEW_Team.setText(_translate("MainWindow", "NEW Team"))
        self.actionOPEN_Team.setText(_translate("MainWindow", "OPEN Team"))
        self.actionSAVE_Team.setText(_translate("MainWindow", "SAVE Team"))
        self.actionEVALUATE_Team.setText(_translate("MainWindow", "EVALUATE Team"))

    def new_team(self):
       self.enable_team()
       self.get_team_name()
       
    def enable_team(self):
       self.groupBox_3.setEnabled(True)
       self.groupBox_2.setEnabled(True)
       self.pushButton.setEnabled(True)
       self.label_2.setText('0')
       self.label_4.setText('0')
       self.label_6.setText('0')
       self.label_8.setText('0')
       self.label_12.setText('0')
       self.radioButton.setChecked(True)
       self.Players_BAT()
       
        
    def get_team_name(self):
        team_name, ok = QtWidgets.QInputDialog.getText(
              None,
              "New Team",
              "Enter Team Name:")
        if ok and team_name:
          self.label_14.setText(team_name)
       
    def Players_BAT(self):
        self.listWidget.clear()
        connection_object = sqlite3.connect('FantasyCricketGame.db')
        cursor_object = connection_object.cursor()
        query='''SELECT Player FROM Stats WHERE Ctg = ? ORDER BY Player'''
        cursor_object.execute(query,('BAT',))
        record=cursor_object.fetchall()
        for i in record:
            self.listWidget.addItem(i[0])
        self.calculate2_points()
        connection_object.commit()
        connection_object.close()
            
    def Players_BOW(self):
        self.listWidget.clear()
        connection_object = sqlite3.connect('FantasyCricketGame.db')
        cursor_object = connection_object.cursor()
        query='''SELECT Player FROM Stats WHERE Ctg = ? ORDER BY Player'''
        cursor_object.execute(query,('BWL',))
        record=cursor_object.fetchall()
        for i in record:
            self.listWidget.addItem(i[0])
        self.calculate2_points()
        connection_object.commit()
        connection_object.close()
        
    def Players_AR(self):
        self.listWidget.clear()
        connection_object = sqlite3.connect('FantasyCricketGame.db')
        cursor_object = connection_object.cursor()
        query='''SELECT Player FROM Stats WHERE Ctg = ? ORDER BY Player'''
        cursor_object.execute(query,('AR',))
        record=cursor_object.fetchall()
        for i in record:
            self.listWidget.addItem(i[0])
        self.calculate2_points()
        connection_object.close()
            
    def Players_WK(self):
        self.listWidget.clear()
        connection_object = sqlite3.connect('FantasyCricketGame.db')
        cursor_object = connection_object.cursor()
        query='''SELECT Player FROM Stats WHERE Ctg = ? ORDER BY Player'''
        cursor_object.execute(query,('WK',))
        record=cursor_object.fetchall()
        for i in record:
            self.listWidget.addItem(i[0])
        self.calculate2_points()
        connection_object.commit()
        connection_object.close()
            
    def calculate2_points(self):
        total_value = 0
        available_points = 1000
        points_used = int(self.label_12.text())
        total_value = available_points - points_used
        self.label_10.setText(str(total_value))
       
    
    def calculate_points(self):
        total = 0
        connection_object = sqlite3.connect('FantasyCricketGame.db')
        cursor_object = connection_object.cursor()
        query='''SELECT Value FROM Stats WHERE Player = ? '''
        index = self.listWidget_2.count()
        for i in range(0,index):
          item = self.listWidget_2.item(i)
          player_name = item.text()
          cursor_object.execute(query,(player_name,))
          record=cursor_object.fetchone()
          if record:
            total +=record[0]
        self.label_12.setText(str(total))
        self.calculate2_points()
        connection_object.commit()
        connection_object.close()

        
    def select_player(self, item):
       self.selected_item = item
       
    def move_player(self):
      if hasattr(self, 'selected_item'):
        player_name = self.selected_item.text()
        role = self.get_role(player_name)
        count = self.count_role(role)
        if role == 'BAT' and int(self.label_2.text()) >= 5:
            msg = "You can't select more than five Batsmen"
            self.show_popup(msg)
            return
        if role == 'BWL' and int(self.label_4.text()) >= 5:
            msg = "You can't select more than five Bowlers"
            self.show_popup(msg)
            return
        if role == 'AR' and int(self.label_6.text()) >= 3:
            msg = "You can't select more than three Allrounders"
            self.show_popup(msg)
            return
        if role == 'WK' and int(self.label_8.text()) >= 1:
            msg = "You can't select more than one Wicket-Keeper"
            self.show_popup(msg)
            return
        if (self.listWidget_2.count() >= 11):
            msg = "Only 11 players allowed"
            self.show_popup(msg)
            return
        if self.same_player(player_name):
            msg = "Same player is not added again"
            self.show_popup(msg)
            return
        
        current_points = int(self.label_12.text())
        player_value = self.get_player_value(player_name)
        if current_points + player_value > 1000:
            self.show_popup("Points exceeded 1000")
            return
        self.listWidget_2.addItem(player_name)
        self.updated_values()
        row = self.listWidget.row(self.selected_item)
        self.listWidget.takeItem(row)
        self.calculate_points()
        
    def same_player(self, player_name):
         for i in range(self.listWidget_2.count()):
           item = self.listWidget_2.item(i).text()
           if item == player_name:
               return True
         return False
        
    def show_menu(self, position):

          menu = QtWidgets.QMenu()
          copy_action = menu.addAction("Copy")
          paste_action = menu.addAction("Paste")
          delete_action = menu.addAction("Delete")
          action = menu.exec_(self.listWidget_2.viewport().mapToGlobal(position))
          if action == copy_action:
              pass
          elif action == paste_action:
              pass
          elif action == delete_action:
           item = self.listWidget_2.currentItem()
           if item:
             row = self.listWidget_2.row(item)
             self.listWidget_2.takeItem(row)
             self.updated_values()
             self.calculate_points()
             
    def get_player_value(self, player_name):
        connection_object = sqlite3.connect('FantasyCricketGame.db')
        cursor_object = connection_object.cursor()
        query = '''SELECT Value FROM Stats WHERE Player = ?'''
        cursor_object.execute(query, (player_name,))
        record = cursor_object.fetchone()
        connection_object.close()
        if record:
            return record[0]
        return 0
        
        
    def get_role(self,player_name):
        connection_object = sqlite3.connect('FantasyCricketGame.db')
        cursor_object = connection_object.cursor()
        query='''SELECT Ctg FROM Stats WHERE Player = ? '''
        cursor_object.execute(query,(player_name,))
        record = cursor_object.fetchone()
        connection_object.close()
        if record :
            return record[0]
        else:
            return 'Invaild'
        

    def count_role(self,role):
        count = 0
        for i in range(self.listWidget_2.count()):
            item = self.listWidget_2.item(i).text()
            role_ply = self.get_role(item)
            if role_ply == role:
                count += 1
            else:
                continue
        return count
            
    def updated_values(self):
        value = str(self.count_role('BAT'))
        value_1 = str(self.count_role('BWL'))
        value_2 = str(self.count_role('AR'))
        value_3 = str(self.count_role('WK'))
        self.label_2.setText(value)
        self.label_4.setText(value_1)
        self.label_6.setText(value_2)
        self.label_8.setText(value_3)
        
    def show_popup(self,msg):
        msg_box = QMessageBox()
        msg_box.setWindowTitle(" ")
        msg_box.setText(msg)
        msg_box.setStandardButtons(QMessageBox.Ok)
        msg_box.exec_()
        
    def save_team(self):
        
        if self.take_item():
          self.update_db()
          self.show_popup("Team Saved Successfully")

    def update_db(self):
        connection_object = sqlite3.connect('FantasyCricketGame.db')
        cursor_object = connection_object.cursor()
        name = self.label_14.text()
        value = self.label_12.text()
        players = []
        for i in range(self.listWidget_2.count()):
            item = self.listWidget_2.item(i).text()
            players.append(item)
        all_players = ",".join(players)
        query='''INSERT INTO Teams(Name,Players,Value) VALUES(?,?,?); '''
        cursor_object.execute(query,(name,all_players,value,))
        connection_object.commit()
        connection_object.close()
        self.reset_screen()
    
    def take_item(self):
        
        if self.listWidget_2.count() != 11:
         self.show_popup("Team must contain exactly 11 players")
         return False
        bat_count = self.count_role('BAT')
        bowl_count = self.count_role('BWL')
        ar_count = self.count_role('AR')
        wk_count = self.count_role('WK')

        if bat_count < 4:
            self.show_popup("There should be minimum 4 Batsmen")
            return False

        if bowl_count < 3:
            self.show_popup("There should be minimum 3 Bowlers")
            return False

        if ar_count < 1:
            self.show_popup("There should be minimum 1 Allrounder")
            return False

        if wk_count < 1:
            self.show_popup("There should be minimum 1 Wicket-Keeper")
            return False

        return True
    
    def open_team(self):
        pass
    
    def reset_screen(self):

        self.listWidget.clear()
        self.listWidget_2.clear()

        self.label_2.setText('0')
        self.label_4.setText('0')
        self.label_6.setText('0')
        self.label_8.setText('0')

        self.label_10.setText('1000')
        self.label_12.setText('0')

        self.label_14.setText('Displayed Here')

        self.groupBox_3.setEnabled(True)
        self.groupBox_2.setEnabled(True)
        self.pushButton.setEnabled(True)
   
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
